#!/bin/bash
#Declaring Variable
a=110

#Printing a Variable using echo Command
echo $a
#Arthimetic Substitution

b=$((10+10))

#command SUBS
DATE=$(date +%F)
echo today date is $DATE

z=100
readonly z
z=200
echo $a

